### ISSUE TITLE
Не удается установить подписку на сообщения пользователя

### ISSUE THREAD

**Issue by andreybordukov** [newcloudtechnologies/squadus-nodejs-botsdk#1]
При тестировании примера https://github.com/newcloudtechnologies/squadus-nodejs-botsdk/blob/master/examples/src/subscribeMessages.ts - не приходят сообщения из директа, при том что отправить сообщения от бота пользователю получается

**Comment by lokorel** [comment]
Сервер https://im-test-20.squadus.ru

**Comment by andreybordukov** [comment]
Да, использовали сервер https://im-test-20.squadus.ru/, 
@squadus/botsdk - versoin: 0.0.1 
node - version: 14.21.3

бот - [BTN-145_bot](https://im-test-20.squadus.ru/direct/BTN-145_bot)

**Comment by aprocom** [comment]
@andreybordukov @lokorel Приветствую! Проблему зафиксировали и сейчас разбираемся в причине. В ближайшее время вернусь с ответом и решением.
Спасибо, за репорт о проблеме!

**Comment by aprocom** [comment]
@andreybordukov @lokorel Приветствую. Проблема работы SDK связана с особенностью конфигурации стенда https://im-test-20.squadus.ru/
Для корректной работы сценария подписки на новые сообщения, нужно выставить параметр в `Admin panel -> Messages -> Show Read Receipts` в состояние включено.
